camera:
  ros__parameters:
    gscam_config: >
      v4l2src device=/dev/video11 io-mode=2 do-timestamp=true !
      video/x-raw,format=NV12,width=2112,height=1568,framerate=15/1,interlace-mode=progressive !
      videoconvert !
      video/x-raw,format=RGB !
      queue leaky=downstream max-size-buffers=1 !
      appsink max-buffers=1 drop=true

    image_encoding: "rgb8"
    frame_id: "camera_link"
    use_sensor_data_qos: true
    use_gst_timestamps: true
    preroll: false
    sync_sink: false
